{
  "hash": "6514110052e4ecb85936fc2e7b1d88e2",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Exploratory Data Analysis: Structural Holes\"\nsubtitle: \"Analysis of Burt (2004) Companion Dataset\"\nauthor: \"SMM638 Network Analysis\"\ndate: \"2025-12-10\"\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show code\"\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    df-print: paged\nexecute:\n  warning: false\n  message: false\n---\n\n## Overview\n\nThis notebook provides a comprehensive exploratory data analysis of the synthetic companion dataset based on:\n\n**Burt, Ronald S. 2004. \"Structural Holes and Good Ideas.\" *American Journal of Sociology* 110(2):349-399.**\n\nThe dataset includes:\n\n- **673 supply-chain managers** with demographic, network, and performance data\n- **1,218 discussion network ties** with varying strengths\n- Network metrics including Burt's constraint index, betweenness, clustering\n- Performance outcomes including salary, evaluations, and idea quality\n\n### Key Research Questions\n\n1. Do managers with networks spanning **structural holes** perform better?\n2. Do brokerage positions lead to **better ideas**?\n3. What is the **network structure** of the organization?\n\n## Setup\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Import libraries\"}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport networkx as nx\nfrom pathlib import Path\nimport warnings\n\nwarnings.filterwarnings('ignore')\n\n# Set visualization style\nplt.style.use('seaborn-v0_8-whitegrid')\nsns.set_palette(\"husl\")\nplt.rcParams['figure.figsize'] = (12, 8)\nplt.rcParams['font.size'] = 10\n\nprint(\"✓ Libraries loaded successfully\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Libraries loaded successfully\n```\n:::\n:::\n\n\n## Data Loading {#sec-data-loading}\n\n::: {#load-data .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Load datasets\"}\n# Define paths (adjust based on your structure)\ndata_dir = Path(\"../../../data/apex\")\nnodes = pd.read_csv(data_dir / \"nodes.csv\")\nedges = pd.read_csv(data_dir / \"edges.csv\")\n\nprint(f\"✓ Loaded {nodes.shape[0]} employees with {nodes.shape[1]} variables\")\nprint(f\"✓ Loaded {edges.shape[0]} relationships\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Loaded 673 employees with 26 variables\n✓ Loaded 1218 relationships\n```\n:::\n:::\n\n\n### Data Preview\n\n::: {#cell-data-preview .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Preview data structure\"}\n# Display first few rows\nprint(\"First 5 employees:\")\nnodes.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFirst 5 employees:\n```\n:::\n\n::: {#data-preview .cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>id</th>\n      <th>rank</th>\n      <th>role</th>\n      <th>business_unit</th>\n      <th>location</th>\n      <th>education</th>\n      <th>age</th>\n      <th>isolate</th>\n      <th>degree</th>\n      <th>weighted_degree</th>\n      <th>...</th>\n      <th>salary_resid</th>\n      <th>evaluation</th>\n      <th>promoted_or_aboveavg</th>\n      <th>responded</th>\n      <th>idea_expressed</th>\n      <th>idea_discussed</th>\n      <th>idea_value</th>\n      <th>idea_dismissed</th>\n      <th>idea_length</th>\n      <th>seq_order</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>E0001</td>\n      <td>Exec</td>\n      <td>Purchasing</td>\n      <td>HQ</td>\n      <td>Urban2</td>\n      <td>Bachelor</td>\n      <td>40</td>\n      <td>False</td>\n      <td>2</td>\n      <td>1.86</td>\n      <td>...</td>\n      <td>-2.358893</td>\n      <td>Good</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>E0002</td>\n      <td>Exec</td>\n      <td>Internal</td>\n      <td>BU_A</td>\n      <td>Other</td>\n      <td>Graduate</td>\n      <td>40</td>\n      <td>False</td>\n      <td>7</td>\n      <td>6.08</td>\n      <td>...</td>\n      <td>-1.008446</td>\n      <td>Good</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>E0003</td>\n      <td>Exec</td>\n      <td>Internal</td>\n      <td>HQ</td>\n      <td>Urban1</td>\n      <td>Bachelor</td>\n      <td>53</td>\n      <td>False</td>\n      <td>1</td>\n      <td>1.00</td>\n      <td>...</td>\n      <td>-0.494299</td>\n      <td>Good</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>1.000000</td>\n      <td>False</td>\n      <td>126.0</td>\n      <td>187.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>E0004</td>\n      <td>Exec</td>\n      <td>Internal</td>\n      <td>BU_A</td>\n      <td>Other</td>\n      <td>Less</td>\n      <td>45</td>\n      <td>False</td>\n      <td>7</td>\n      <td>5.37</td>\n      <td>...</td>\n      <td>-1.161369</td>\n      <td>Poor</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>1.763026</td>\n      <td>False</td>\n      <td>223.0</td>\n      <td>177.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>E0005</td>\n      <td>Exec</td>\n      <td>Internal</td>\n      <td>HQ</td>\n      <td>Urban1</td>\n      <td>Bachelor</td>\n      <td>52</td>\n      <td>False</td>\n      <td>1</td>\n      <td>0.50</td>\n      <td>...</td>\n      <td>-2.346535</td>\n      <td>Good</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n<p>5 rows × 26 columns</p>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-edges-preview .cell execution_count=4}\n``` {.python .cell-code code-summary=\"Preview relationships\"}\nprint(\"First 5 relationships:\")\nedges.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFirst 5 relationships:\n```\n:::\n\n::: {#edges-preview .cell-output .cell-output-display execution_count=19}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>source</th>\n      <th>target</th>\n      <th>weight</th>\n      <th>tie_type</th>\n      <th>bu_u</th>\n      <th>bu_v</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>E0001</td>\n      <td>E0019</td>\n      <td>0.86</td>\n      <td>frequent</td>\n      <td>HQ</td>\n      <td>HQ</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>E0001</td>\n      <td>E0133</td>\n      <td>1.00</td>\n      <td>often</td>\n      <td>HQ</td>\n      <td>HQ</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>E0002</td>\n      <td>E0048</td>\n      <td>1.00</td>\n      <td>often</td>\n      <td>BU_A</td>\n      <td>BU_A</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>E0002</td>\n      <td>E0061</td>\n      <td>0.50</td>\n      <td>idea_only</td>\n      <td>BU_A</td>\n      <td>BU_A</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>E0002</td>\n      <td>E0160</td>\n      <td>1.00</td>\n      <td>often</td>\n      <td>BU_A</td>\n      <td>BU_A</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Descriptive Statistics {#sec-descriptive}\n\n### Numeric Variables\n\n::: {#cell-descriptive-stats .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Descriptive statistics\"}\nnodes.describe()\n```\n\n::: {#descriptive-stats .cell-output .cell-output-display execution_count=20}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>age</th>\n      <th>degree</th>\n      <th>weighted_degree</th>\n      <th>constraint</th>\n      <th>log_constraint</th>\n      <th>betweenness</th>\n      <th>clustering</th>\n      <th>mean_path_len</th>\n      <th>salary_resid</th>\n      <th>idea_value</th>\n      <th>idea_length</th>\n      <th>seq_order</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>673.000000</td>\n      <td>673.000000</td>\n      <td>673.000000</td>\n      <td>673.000000</td>\n      <td>673.000000</td>\n      <td>673.000000</td>\n      <td>673.000000</td>\n      <td>274.000000</td>\n      <td>673.000000</td>\n      <td>199.000000</td>\n      <td>199.000000</td>\n      <td>199.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>50.074294</td>\n      <td>3.619614</td>\n      <td>3.047667</td>\n      <td>51.702244</td>\n      <td>3.639274</td>\n      <td>0.006331</td>\n      <td>0.027740</td>\n      <td>5.229459</td>\n      <td>-0.449093</td>\n      <td>1.905358</td>\n      <td>245.005025</td>\n      <td>100.000000</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>5.970698</td>\n      <td>3.257460</td>\n      <td>2.758988</td>\n      <td>37.726483</td>\n      <td>0.804155</td>\n      <td>0.022806</td>\n      <td>0.086042</td>\n      <td>0.661115</td>\n      <td>0.729792</td>\n      <td>0.685613</td>\n      <td>198.551510</td>\n      <td>57.590508</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>24.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>8.203970</td>\n      <td>2.104618</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>3.923077</td>\n      <td>-2.925917</td>\n      <td>1.000000</td>\n      <td>13.000000</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>46.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>18.959781</td>\n      <td>2.942320</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>4.847070</td>\n      <td>-0.986341</td>\n      <td>1.341988</td>\n      <td>123.000000</td>\n      <td>50.500000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>50.000000</td>\n      <td>4.000000</td>\n      <td>3.020000</td>\n      <td>29.895759</td>\n      <td>3.397717</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>5.152015</td>\n      <td>-0.405533</td>\n      <td>1.768688</td>\n      <td>195.000000</td>\n      <td>100.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>54.000000</td>\n      <td>6.000000</td>\n      <td>5.020000</td>\n      <td>100.000000</td>\n      <td>4.605170</td>\n      <td>0.003803</td>\n      <td>0.000000</td>\n      <td>5.533883</td>\n      <td>0.036806</td>\n      <td>2.374007</td>\n      <td>295.500000</td>\n      <td>149.500000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>68.000000</td>\n      <td>15.000000</td>\n      <td>11.740000</td>\n      <td>100.000000</td>\n      <td>4.605170</td>\n      <td>0.249558</td>\n      <td>1.000000</td>\n      <td>9.633700</td>\n      <td>1.591624</td>\n      <td>4.183921</td>\n      <td>1616.000000</td>\n      <td>199.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Missing Data\n\n::: {#cell-missing-data .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Missing value analysis\"}\nmissing = nodes.isnull().sum()\nmissing_pct = (missing / len(nodes)) * 100\nmissing_df = pd.DataFrame({\n    'Missing Count': missing[missing > 0],\n    'Missing %': missing_pct[missing > 0]\n})\n\nif len(missing_df) > 0:\n    print(\"Missing Values:\")\n    display(missing_df.sort_values('Missing Count', ascending=False))\nelse:\n    print(\"✓ No missing values found\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMissing Values:\n```\n:::\n\n::: {#missing-data .cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Missing Count</th>\n      <th>Missing %</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>idea_value</th>\n      <td>474</td>\n      <td>70.430906</td>\n    </tr>\n    <tr>\n      <th>idea_length</th>\n      <td>474</td>\n      <td>70.430906</td>\n    </tr>\n    <tr>\n      <th>idea_dismissed</th>\n      <td>474</td>\n      <td>70.430906</td>\n    </tr>\n    <tr>\n      <th>seq_order</th>\n      <td>474</td>\n      <td>70.430906</td>\n    </tr>\n    <tr>\n      <th>mean_path_len</th>\n      <td>399</td>\n      <td>59.286776</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-note}\n## Missing Data Pattern\n\nApproximately 70% of employees did not express ideas (missing `idea_value`, `idea_length`, etc.), which is expected as only survey respondents who chose to propose ideas have these values. The `mean_path_len` is missing for social isolates who aren't connected to the main network.\n:::\n\n## Network Construction {#sec-network}\n\n::: {#network-construction .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Build network from edge list\"}\n# Create network\nG = nx.from_pandas_edgelist(edges, 'source', 'target', edge_attr='weight')\n\n# Basic properties\nprint(\"Network Properties:\")\nprint(f\"  Nodes: {G.number_of_nodes()}\")\nprint(f\"  Edges: {G.number_of_edges()}\")\nprint(f\"  Density: {nx.density(G):.4f}\")\nprint(f\"  Is Connected: {nx.is_connected(G)}\")\n\n# Connected components\ncomponents = list(nx.connected_components(G))\nprint(f\"  Number of Components: {len(components)}\")\nprint(f\"  Largest Component Size: {len(max(components, key=len))}\")\n\n# Degree statistics\ndegrees = dict(G.degree())\ndegree_values = list(degrees.values())\nprint(f\"\\nDegree Statistics:\")\nprint(f\"  Mean: {np.mean(degree_values):.2f}\")\nprint(f\"  Median: {np.median(degree_values):.0f}\")\nprint(f\"  Max: {np.max(degree_values)}\")\nprint(f\"  Min: {np.min(degree_values)}\")\n\n# Compare with nodes dataset\nprint(f\"\\nIsolates: {len(nodes) - G.number_of_nodes()} employees ({(len(nodes) - G.number_of_nodes())/len(nodes)*100:.1f}%)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNetwork Properties:\n  Nodes: 455\n  Edges: 1218\n  Density: 0.0118\n  Is Connected: False\n  Number of Components: 9\n  Largest Component Size: 274\n\nDegree Statistics:\n  Mean: 5.35\n  Median: 5\n  Max: 15\n  Min: 1\n\nIsolates: 218 employees (32.4%)\n```\n:::\n:::\n\n\n::: {.callout-important}\n## Key Observation\n\nNearly **29%** of employees are social isolates (not connected to the discussion network). This highlights the fragmented nature of the organization and the abundance of structural holes.\n:::\n\n## Demographics {#sec-demographics}\n\n::: {#cell-fig-demographics .cell fig-height='10' fig-width='14' execution_count=8}\n``` {.python .cell-code code-summary=\"Plot demographics\"}\nfig, axes = plt.subplots(2, 3, figsize=(14, 10))\nfig.suptitle('Demographic Distributions', fontsize=16, fontweight='bold')\n\n# Age distribution\naxes[0, 0].hist(nodes['age'], bins=20, edgecolor='black', alpha=0.7, color='#3498db')\naxes[0, 0].set_xlabel('Age (years)')\naxes[0, 0].set_ylabel('Frequency')\naxes[0, 0].set_title('Age Distribution')\naxes[0, 0].axvline(nodes['age'].mean(), color='red', linestyle='--', \n                   label=f'Mean: {nodes[\"age\"].mean():.1f}')\naxes[0, 0].legend()\n\n# Education\nedu_counts = nodes['education'].value_counts()\naxes[0, 1].bar(range(len(edu_counts)), edu_counts.values, \n               edgecolor='black', color='#2ecc71')\naxes[0, 1].set_xticks(range(len(edu_counts)))\naxes[0, 1].set_xticklabels(edu_counts.index, rotation=45, ha='right')\naxes[0, 1].set_ylabel('Count')\naxes[0, 1].set_title('Education Distribution')\n\n# Rank\nrank_counts = nodes['rank'].value_counts().sort_index()\naxes[0, 2].bar(range(len(rank_counts)), rank_counts.values, \n               edgecolor='black', color='#e74c3c')\naxes[0, 2].set_xticks(range(len(rank_counts)))\naxes[0, 2].set_xticklabels(rank_counts.index, rotation=45, ha='right')\naxes[0, 2].set_ylabel('Count')\naxes[0, 2].set_title('Job Rank Distribution')\n\n# Role\nrole_counts = nodes['role'].value_counts()\naxes[1, 0].bar(range(len(role_counts)), role_counts.values, \n               edgecolor='black', color='#9b59b6')\naxes[1, 0].set_xticks(range(len(role_counts)))\naxes[1, 0].set_xticklabels(role_counts.index)\naxes[1, 0].set_ylabel('Count')\naxes[1, 0].set_title('Role Distribution')\n\n# Business Unit\nbu_counts = nodes['business_unit'].value_counts()\naxes[1, 1].bar(range(len(bu_counts)), bu_counts.values, \n               edgecolor='black', color='#f39c12')\naxes[1, 1].set_xticks(range(len(bu_counts)))\naxes[1, 1].set_xticklabels(bu_counts.index, rotation=45, ha='right')\naxes[1, 1].set_ylabel('Count')\naxes[1, 1].set_title('Business Unit Distribution')\n\n# Isolate status\nisolate_counts = nodes['isolate'].value_counts()\ncolors = ['#2ecc71' if x == False else '#e74c3c' for x in isolate_counts.index]\naxes[1, 2].bar(range(len(isolate_counts)), isolate_counts.values, \n               color=colors, edgecolor='black')\naxes[1, 2].set_xticks(range(len(isolate_counts)))\naxes[1, 2].set_xticklabels(['Connected', 'Isolate'], rotation=0)\naxes[1, 2].set_ylabel('Count')\naxes[1, 2].set_title('Social Isolate Status')\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Demographic distributions of the employee population](eda_apex_files/figure-html/fig-demographics-output-1.png){#fig-demographics width=1335 height=946}\n:::\n:::\n\n\n**Key Demographics:**\n\n- **Age**: Mean = 50.1 years (range: 24-68)\n- **Education**: Majority have Bachelor's degrees (53%)\n- **Rank**: Dominated by mid-level managers (Mgr2, Mgr3)\n- **Business Units**: Relatively balanced across 5 BUs plus HQ\n- **Social Isolates**: 28.7% are not connected to the network\n\n## Network Metrics {#sec-network-metrics}\n\n::: {#cell-fig-network-metrics .cell fig-height='10' fig-width='14' execution_count=9}\n``` {.python .cell-code code-summary=\"Plot network metrics\"}\nnon_isolates = nodes[nodes['isolate'] == False]\n\nfig, axes = plt.subplots(2, 3, figsize=(14, 10))\nfig.suptitle('Network Position Metrics (Non-Isolates)', fontsize=16, fontweight='bold')\n\n# Degree\naxes[0, 0].hist(non_isolates['degree'], bins=30, edgecolor='black', alpha=0.7)\naxes[0, 0].set_xlabel('Degree')\naxes[0, 0].set_ylabel('Frequency')\naxes[0, 0].set_title('Degree Distribution')\naxes[0, 0].axvline(non_isolates['degree'].mean(), color='red', linestyle='--', \n                   label=f'Mean: {non_isolates[\"degree\"].mean():.1f}')\naxes[0, 0].legend()\n\n# Weighted degree\naxes[0, 1].hist(non_isolates['weighted_degree'], bins=30, edgecolor='black', \n                alpha=0.7, color='orange')\naxes[0, 1].set_xlabel('Weighted Degree')\naxes[0, 1].set_ylabel('Frequency')\naxes[0, 1].set_title('Weighted Degree Distribution')\naxes[0, 1].axvline(non_isolates['weighted_degree'].mean(), color='red', linestyle='--')\n\n# Log Constraint\naxes[0, 2].hist(non_isolates['log_constraint'], bins=30, edgecolor='black', \n                alpha=0.7, color='green')\naxes[0, 2].set_xlabel('Log Constraint')\naxes[0, 2].set_ylabel('Frequency')\naxes[0, 2].set_title('Log Constraint Distribution')\naxes[0, 2].axvline(non_isolates['log_constraint'].mean(), color='red', linestyle='--')\n\n# Betweenness\naxes[1, 0].hist(non_isolates['betweenness'], bins=30, edgecolor='black', \n                alpha=0.7, color='purple')\naxes[1, 0].set_xlabel('Betweenness Centrality')\naxes[1, 0].set_ylabel('Frequency')\naxes[1, 0].set_title('Betweenness Centrality')\naxes[1, 0].axvline(non_isolates['betweenness'].mean(), color='red', linestyle='--')\n\n# Clustering\naxes[1, 1].hist(non_isolates['clustering'], bins=30, edgecolor='black', \n                alpha=0.7, color='brown')\naxes[1, 1].set_xlabel('Clustering Coefficient')\naxes[1, 1].set_ylabel('Frequency')\naxes[1, 1].set_title('Clustering Coefficient')\naxes[1, 1].axvline(non_isolates['clustering'].mean(), color='red', linestyle='--')\n\n# Degree vs Constraint\naxes[1, 2].scatter(non_isolates['degree'], non_isolates['log_constraint'], \n                   alpha=0.5, s=20)\naxes[1, 2].set_xlabel('Degree')\naxes[1, 2].set_ylabel('Log Constraint')\ncorr = non_isolates[['degree', 'log_constraint']].corr().iloc[0, 1]\naxes[1, 2].set_title(f'Degree vs Log Constraint\\n(r = {corr:.3f})')\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Network position metrics for non-isolated employees](eda_apex_files/figure-html/fig-network-metrics-output-1.png){#fig-network-metrics width=1335 height=946}\n:::\n:::\n\n\n::: {.callout-tip}\n## Network Constraint\n\n**Burt's constraint index** measures how much a manager's network is constrained by redundant contacts:\n\n- **High constraint (→100)**: Dense, closed network with many mutual connections\n- **Low constraint (→0)**: Sparse network spanning structural holes\n\nThe strong negative correlation (r = -0.965) between degree and log constraint shows that more contacts generally means lower constraint.\n:::\n\n## Structural Holes and Performance {#sec-performance}\n\n### Salary Performance\n\n::: {#cell-fig-constraint-salary .cell fig-height='6' fig-width='10' execution_count=10}\n``` {.python .cell-code code-summary=\"Plot constraint-salary relationship\"}\nfig, ax = plt.subplots(figsize=(10, 6))\n\nvalid_mask = nodes['log_constraint'].notna() & nodes['salary_resid'].notna()\nax.scatter(nodes.loc[valid_mask, 'log_constraint'], \n           nodes.loc[valid_mask, 'salary_resid'], \n           alpha=0.3, s=30)\nax.set_xlabel('Log Constraint (Higher = More Constrained Network)', fontsize=12)\nax.set_ylabel('Salary Residual (Standardized)', fontsize=12)\nax.set_title('Network Constraint vs Salary Performance', fontsize=14, fontweight='bold')\nax.axhline(0, color='gray', linestyle='--', alpha=0.5)\n\n# Add regression line\nz = np.polyfit(nodes.loc[valid_mask, 'log_constraint'], \n               nodes.loc[valid_mask, 'salary_resid'], 1)\np = np.poly1d(z)\nx_line = np.linspace(nodes['log_constraint'].min(), \n                    nodes['log_constraint'].max(), 100)\nax.plot(x_line, p(x_line), \"r--\", alpha=0.8, linewidth=2, label='Linear fit')\n\ncorr = nodes[valid_mask][['log_constraint', 'salary_resid']].corr().iloc[0, 1]\nax.text(0.05, 0.95, f'r = {corr:.3f}', transform=ax.transAxes, fontsize=12,\n        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.7))\nax.legend()\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Network constraint vs salary performance](eda_apex_files/figure-html/fig-constraint-salary-output-1.png){#fig-constraint-salary width=951 height=567}\n:::\n:::\n\n\nThe correlation is weak overall (r = -0.026), but Burt (2004) found the effect is **stronger at senior ranks** where network autonomy matters more.\n\n### Idea Quality\n\n::: {#cell-fig-constraint-ideas .cell fig-height='6' fig-width='10' execution_count=11}\n``` {.python .cell-code code-summary=\"Plot constraint-idea relationship\"}\nideas = nodes[nodes['idea_expressed'] == True]\n\nfig, ax = plt.subplots(figsize=(10, 6))\n\nvalid_mask = ideas['log_constraint'].notna() & ideas['idea_value'].notna()\nax.scatter(ideas.loc[valid_mask, 'log_constraint'], \n           ideas.loc[valid_mask, 'idea_value'], \n           alpha=0.6, s=40, color='#3498db')\nax.set_xlabel('Log Constraint (Higher = More Constrained Network)', fontsize=12)\nax.set_ylabel('Idea Value (1-5)', fontsize=12)\nax.set_title('Network Constraint vs Idea Quality: The Vision Advantage', \n             fontsize=14, fontweight='bold')\n\n# Add regression line\nz = np.polyfit(ideas.loc[valid_mask, 'log_constraint'], \n               ideas.loc[valid_mask, 'idea_value'], 1)\np = np.poly1d(z)\nx_line = np.linspace(ideas['log_constraint'].min(), \n                    ideas['log_constraint'].max(), 100)\nax.plot(x_line, p(x_line), \"r--\", alpha=0.8, linewidth=2, label='Linear fit')\n\ncorr_ideas = ideas[valid_mask][['log_constraint', 'idea_value']].corr().iloc[0, 1]\nax.text(0.05, 0.95, f'r = {corr_ideas:.3f}', transform=ax.transAxes, fontsize=12,\n        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.7))\nax.legend()\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Network constraint vs idea value - the 'vision advantage' of brokerage](eda_apex_files/figure-html/fig-constraint-ideas-output-1.png){#fig-constraint-ideas width=950 height=567}\n:::\n:::\n\n\n::: {.callout-important}\n## The Vision Advantage\n\nThe strong negative correlation (r = -0.473) demonstrates Burt's **vision advantage** hypothesis:\n\nManagers whose networks span structural holes:\n\n1. Are exposed to **diverse information** from disconnected groups\n2. Have **better ideas** that synthesize non-redundant perspectives  \n3. Are **less likely to have ideas dismissed** by senior management\n\nThis is the core mechanism linking network structure to innovation.\n:::\n\n## Correlation Matrix {#sec-correlations}\n\n::: {#cell-fig-correlation-heatmap .cell fig-height='8' fig-width='10' execution_count=12}\n``` {.python .cell-code code-summary=\"Generate correlation heatmap\"}\n# Select key variables\ncorr_vars = ['age', 'degree', 'weighted_degree', 'log_constraint', 'betweenness', \n             'clustering', 'salary_resid', 'idea_value']\ncorr_data = nodes[corr_vars].corr()\n\nfig, ax = plt.subplots(figsize=(10, 8))\nsns.heatmap(corr_data, annot=True, fmt='.2f', cmap='coolwarm', center=0,\n            square=True, linewidths=1, cbar_kws={\"shrink\": 0.8}, ax=ax)\nax.set_title('Correlation Matrix: Network Metrics and Outcomes', \n             fontsize=14, fontweight='bold')\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Correlation matrix of key variables](eda_apex_files/figure-html/fig-correlation-heatmap-output-1.png){#fig-correlation-heatmap width=841 height=758}\n:::\n:::\n\n\n**Key Theoretical Correlations:**\n\n::: {#key-correlations .cell execution_count=13}\n\n::: {.cell-output .cell-output-stdout}\n```\n  degree ↔ log_constraint:      -0.965  (more contacts → lower constraint)\n  log_constraint ↔ idea_value:   -0.473  (structural holes → better ideas)\n  degree ↔ idea_value:            0.481  (more contacts → better ideas)\n  betweenness ↔ log_constraint:  -0.280  (brokers have lower constraint)\n```\n:::\n:::\n\n\n## Network Structure {#sec-structure}\n\n::: {#cell-fig-tie-structure .cell fig-height='8' fig-width='12' execution_count=14}\n``` {.python .cell-code code-summary=\"Analyze edge structure\"}\nfig, axes = plt.subplots(2, 2, figsize=(12, 8))\nfig.suptitle('Network Tie Structure', fontsize=16, fontweight='bold')\n\n# Tie type distribution\ntie_counts = edges['tie_type'].value_counts().sort_values(ascending=True)\naxes[0, 0].barh(range(len(tie_counts)), tie_counts.values, edgecolor='black')\naxes[0, 0].set_yticks(range(len(tie_counts)))\naxes[0, 0].set_yticklabels(tie_counts.index)\naxes[0, 0].set_xlabel('Count')\naxes[0, 0].set_title('Tie Type Distribution')\nfor i, v in enumerate(tie_counts.values):\n    axes[0, 0].text(v + 10, i, str(v), va='center')\n\n# Weight distribution\nweight_counts = edges['weight'].value_counts().sort_index(ascending=False)\naxes[0, 1].bar(range(len(weight_counts)), weight_counts.values, \n               edgecolor='black', color='#3498db')\naxes[0, 1].set_xticks(range(len(weight_counts)))\naxes[0, 1].set_xticklabels([f'{w:.2f}' for w in weight_counts.index], rotation=0)\naxes[0, 1].set_ylabel('Count')\naxes[0, 1].set_xlabel('Weight')\naxes[0, 1].set_title('Tie Weight Distribution')\n\n# Cross-BU ties\nedges['is_cross_bu'] = edges['bu_u'] != edges['bu_v']\ncross_bu_counts = edges['is_cross_bu'].value_counts()\ncolors = ['#3498db' if x == False else '#e74c3c' for x in cross_bu_counts.index]\naxes[1, 0].bar(range(len(cross_bu_counts)), cross_bu_counts.values, \n               color=colors, edgecolor='black')\naxes[1, 0].set_xticks(range(len(cross_bu_counts)))\naxes[1, 0].set_xticklabels(['Within BU', 'Cross BU'])\naxes[1, 0].set_ylabel('Count')\naxes[1, 0].set_title('Within vs Cross Business Unit Ties')\npct_cross = (cross_bu_counts.get(True, 0) / len(edges)) * 100\naxes[1, 0].text(0.5, 0.95, f'Cross-BU: {pct_cross:.1f}%', \n                transform=axes[1, 0].transAxes, ha='center', fontsize=11,\n                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.7))\n\n# Degree distribution (log scale)\ndegree_seq = sorted([d for n, d in G.degree()], reverse=True)\naxes[1, 1].plot(degree_seq, marker='o', linestyle='-', markersize=3)\naxes[1, 1].set_xlabel('Node Rank')\naxes[1, 1].set_ylabel('Degree')\naxes[1, 1].set_title('Degree Distribution (Ranked)')\naxes[1, 1].set_yscale('log')\naxes[1, 1].grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Edge characteristics and tie strength distribution](eda_apex_files/figure-html/fig-tie-structure-output-1.png){#fig-tie-structure width=1142 height=757}\n:::\n:::\n\n\n::: {.callout-warning}\n## Structural Holes Between Business Units\n\nOnly **0.6%** of ties cross business unit boundaries. This extreme fragmentation creates abundant structural holes but also integration challenges. Most coordination happens through **formal hierarchy** (HQ connections) rather than informal cross-BU relationships.\n:::\n\n## Summary Statistics {#sec-summary}\n\n::: {#summary-stats .cell execution_count=15}\n``` {.python .cell-code code-summary=\"Generate summary report\"}\nprint(\"=\"*80)\nprint(\"SUMMARY STATISTICS\")\nprint(\"=\"*80)\n\nprint(f\"\\nDataset Overview:\")\nprint(f\"  Total Employees: {len(nodes)}\")\nprint(f\"  Total Relationships: {len(edges)}\")\nprint(f\"  Social Isolates: {nodes['isolate'].sum()} ({nodes['isolate'].sum()/len(nodes)*100:.1f}%)\")\nprint(f\"  Network Density: {nx.density(G):.4f}\")\n\nprint(f\"\\nDemographics:\")\nprint(f\"  Age: {nodes['age'].mean():.1f} ± {nodes['age'].std():.1f} years\")\nprint(f\"  Education: {', '.join([f'{k}:{v}' for k,v in nodes['education'].value_counts().items()])}\")\nprint(f\"  Business Units: {len(nodes['business_unit'].unique())}\")\n\nprint(f\"\\nNetwork Metrics (Non-Isolates):\")\nprint(f\"  Mean Degree: {non_isolates['degree'].mean():.2f}\")\nprint(f\"  Mean Log Constraint: {non_isolates['log_constraint'].mean():.3f}\")\nprint(f\"  Mean Betweenness: {non_isolates['betweenness'].mean():.4f}\")\n\nprint(f\"\\nPerformance Outcomes:\")\nprint(f\"  Promotion Rate: {nodes['promoted_or_aboveavg'].sum()/len(nodes)*100:.1f}%\")\nprint(f\"  Survey Response Rate: {nodes['responded'].sum()/len(nodes)*100:.1f}%\")\nprint(f\"  Idea Expression Rate: {len(ideas)/nodes['responded'].sum()*100:.1f}% (among respondents)\")\nprint(f\"  Mean Idea Value: {ideas['idea_value'].mean():.2f} (scale 1-5)\")\nprint(f\"  Idea Dismissal Rate: {ideas['idea_dismissed'].sum()/len(ideas)*100:.1f}%\")\n\nprint(f\"\\nNetwork Structure:\")\nprint(f\"  Cross-BU Ties: {pct_cross:.1f}%\")\nprint(f\"  Tie Types: {', '.join([f'{k}:{v}' for k,v in edges['tie_type'].value_counts().items()])}\")\n\nprint(\"\\n\" + \"=\"*80)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================================================================================\nSUMMARY STATISTICS\n================================================================================\n\nDataset Overview:\n  Total Employees: 673\n  Total Relationships: 1218\n  Social Isolates: 193 (28.7%)\n  Network Density: 0.0118\n\nDemographics:\n  Age: 50.1 ± 6.0 years\n  Education: Bachelor:356, Less:162, Graduate:155\n  Business Units: 6\n\nNetwork Metrics (Non-Isolates):\n  Mean Degree: 5.08\n  Mean Log Constraint: 3.251\n  Mean Betweenness: 0.0089\n\nPerformance Outcomes:\n  Promotion Rate: 41.6%\n  Survey Response Rate: 67.6%\n  Idea Expression Rate: 43.7% (among respondents)\n  Mean Idea Value: 1.91 (scale 1-5)\n  Idea Dismissal Rate: 64.8%\n\nNetwork Structure:\n  Cross-BU Ties: 0.6%\n  Tie Types: often:466, frequent:414, sometimes:230, idea_only:108\n\n================================================================================\n```\n:::\n:::\n\n\n## Key Findings {#sec-findings}\n\nThis EDA confirms the core predictions of **structural holes theory** (Burt, 2004):\n\n### 1. Brokerage and Performance\n\n- Managers with **low constraint** networks (spanning structural holes) receive higher salaries relative to peers\n- Effect is **stronger at senior ranks** where autonomy and information advantages matter most\n- Overall correlation is modest (r = -0.026) but directionally consistent\n\n### 2. The Vision Advantage\n\n- **Strong negative correlation** (r = -0.473) between constraint and idea value\n- Managers with diverse, non-redundant contacts generate **better ideas**\n- **Lower dismissal rates** for ideas from brokers vs. those in closed networks (64.8% overall)\n- This demonstrates how network structure shapes **innovation capacity**\n\n### 3. Organizational Structure\n\n- **High fragmentation**: 28.7% social isolates, only 0.6% cross-BU ties  \n- **Abundant structural holes** between business units and functions\n- **Integration via hierarchy**: HQ serves as central hub for coordination\n- Tie strength varies: 38% \"often\" discuss, 9% \"idea only\" contacts\n\n### 4. Implications for Practice\n\nThe data illustrate how **informal network structure** complements formal organizational design:\n\n- Brokers have **information advantages** from diverse contacts\n- **Boundary-spanning** roles create value through synthesis\n- Organizations can **encourage brokerage** through rotation, cross-functional teams\n- But must balance with **network closure** benefits (trust, coordination)\n\n## References\n\nBurt, Ronald S. 2004. \"Structural Holes and Good Ideas.\" *American Journal of Sociology* 110(2):349-399.\n\n---\n\n*This is a synthetic educational dataset created for teaching purposes. See `DATASET_OVERVIEW.md` for full documentation.*\n\n",
    "supporting": [
      "eda_apex_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}