{
  "hash": "c5618620ef73edd7be865d83a57943b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Influencer Selection Analysis: The 2�2 Framework\"\nsubtitle: \"Identifying Optimal Candidates Based on Network Size and Diversity\"\ndate: \"today\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    code-summary: \"Show code\"\n---\n\n## Executive Summary\n\nThis analysis applies the strategic framework from the Twitch case study to identify optimal influencers for Space Games Inc.'s \"Thrive in Space 5\" campaign. Using network analysis in R, we implement a **2�2 framework** that evaluates candidates on two critical dimensions:\n\n1. **Network Size** (degree centrality): How many connections does the influencer have?\n2. **Network Diversity** (effective size/constraint): How diverse and non-redundant are those connections?\n\nThe analysis filters for appropriate candidates (non-mature content, affiliate status), calculates centrality measures, and visualizes results using a quadrant framework to identify the most strategic influencers.\n\n::: {.callout-important}\n## Key Finding\nThe best influencer candidates are those with **both large contact networks AND diverse, non-redundant connections** positioned in the upper-right quadrant of our 2x2 matrix.\n:::\n\n\n\n## 1. Setup and Data Loading\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(tidyverse)\nlibrary(igraph)\nlibrary(ggplot2)\nlibrary(scales)\nlibrary(knitr)\nlibrary(gridExtra)\nlibrary(RColorBrewer)\n\n# Set theme for plots\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read Twitch network data\nedges <- read_csv(\"../../../data/twitch/Twitch_edges.csv\")\nnodes <- read_csv(\"../../../data/twitch/Twitch_nodes.csv\")\n\ncat(\"Network structure:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNetwork structure:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- Nodes:\", nrow(nodes), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Nodes: 7126 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- Edges:\", nrow(edges), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Edges: 35324 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- Potential edges:\", nrow(nodes) * (nrow(nodes) - 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Potential edges: 50772750 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- Density:\", round(nrow(edges) / (nrow(nodes) * (nrow(nodes) - 1)), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Density: 7e-04 \n```\n\n\n:::\n:::\n\n\n## 2. Business Filtering Criteria\n\nFollowing the case discussion, we apply two critical business filters before analyzing network position:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Apply business filters\nfiltered_nodes <- nodes %>%\n  filter(\n    Mature_content == FALSE,  # Age-appropriate content for 16+ game\n    Affiliate == TRUE         # Professional monetization capability\n  )\n\ncat(\"\\n=== FILTERING RESULTS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== FILTERING RESULTS ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Original candidates:\", nrow(nodes), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOriginal candidates: 7126 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"After removing mature content:\", sum(!nodes$Mature_content),\n    \"(\", round(sum(!nodes$Mature_content)/nrow(nodes)*100, 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAfter removing mature content: 3238 ( 45.4 %)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Final qualified candidates:\", nrow(filtered_nodes),\n    \"(\", round(nrow(filtered_nodes)/nrow(nodes)*100, 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFinal qualified candidates: 197 ( 2.8 %)\n```\n\n\n:::\n\n```{.r .cell-code}\n# Get IDs of qualified candidates\nqualified_ids <- filtered_nodes$ID\n```\n:::\n\n\n::: {.callout-note}\n## Filtering Rationale\n\n**Mature Content Exclusion**: Space Games Inc. is targeting 16-25 year olds with a family-friendly space strategy game. Mature content channels create brand misalignment and potential PR risks.\n\n**Affiliate Requirement**: Affiliate streamers have proven monetization experience, understand sponsored content disclosure requirements (FTC compliance), and have demonstrated commitment to professional streaming.\n:::\n\n## 3. Network Construction\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create full network\ng_full <- graph_from_data_frame(d = edges, vertices = nodes$ID, directed = TRUE)\n\n# Create subgraph with only qualified candidates\ng_qualified <- induced_subgraph(g_full, vids = as.character(qualified_ids))\n\ncat(\"\\n=== NETWORK STRUCTURE ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== NETWORK STRUCTURE ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Full network:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFull network:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Nodes:\", vcount(g_full), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Nodes: 7126 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Edges:\", ecount(g_full), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Edges: 35324 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nQualified candidates network:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nQualified candidates network:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Nodes:\", vcount(g_qualified), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Nodes: 197 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Edges:\", ecount(g_qualified), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Edges: 355 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Density:\", round(edge_density(g_qualified), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Density: 0.0092 \n```\n\n\n:::\n:::\n\n\n## 4. The 2x2 Framework: Network Size vs. Network Diversity\n\n### 4.1 Dimension 1: Network Size (Degree Centrality)\n\nNetwork size measures how many direct connections an influencer has. In the Twitch context, this represents:\n\n- **Out-degree**: Number of streamers this person follows (reach potential)\n- **In-degree**: Number of followers (direct audience)\n- **Total degree**: Overall network connectivity\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate degree centrality measures\ndegree_metrics <- data.frame(\n  ID = as.numeric(V(g_qualified)$name),\n  in_degree = degree(g_qualified, mode = \"in\"),\n  out_degree = degree(g_qualified, mode = \"out\"),\n  total_degree = degree(g_qualified, mode = \"all\")\n) %>%\n  arrange(desc(total_degree))\n\n# Summary statistics\ncat(\"\\n=== DEGREE CENTRALITY SUMMARY ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== DEGREE CENTRALITY SUMMARY ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nIn-Degree (Followers within qualified network):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nIn-Degree (Followers within qualified network):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(degree_metrics$in_degree))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   1.000   1.802   2.000  17.000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nOut-Degree (Following within qualified network):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOut-Degree (Following within qualified network):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(degree_metrics$out_degree))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   1.000   1.802   2.000  20.000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nTotal Degree:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTotal Degree:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(degree_metrics$total_degree))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   1.000   2.000   3.604   4.000  23.000 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Top 10 by network size\ncat(\"\\n=== TOP 10 BY NETWORK SIZE ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== TOP 10 BY NETWORK SIZE ===\n```\n\n\n:::\n\n```{.r .cell-code}\ntop_degree <- degree_metrics %>%\n  head(10) %>%\n  left_join(nodes, by = \"ID\") %>%\n  select(ID, Channel_ID, total_degree, in_degree, out_degree, Views)\n\nkable(top_degree, caption = \"Top 10 Streamers by Total Degree Centrality\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Streamers by Total Degree Centrality\n\n|   ID| Channel_ID| total_degree| in_degree| out_degree|    Views|\n|----:|----------:|------------:|---------:|----------:|--------:|\n| 1924|   60264946|           23|         3|         20| 15814669|\n| 2740|   27121969|           22|         6|         16| 13481914|\n| 5842|    3481156|           20|        16|          4|  7448777|\n| 4949|   23735582|           20|        17|          3| 46682923|\n| 4374|   65939429|           18|        12|          6|   926412|\n| 6716|   71040143|           17|         7|         10|   971621|\n| 5969|   54146574|           16|        15|          1|  2805793|\n| 5428|      12665|           15|        10|          5| 24316020|\n|  166|   54739364|           15|         0|         15| 20516537|\n| 5979|   39892516|           14|        14|          0|   725379|\n\n\n:::\n:::\n\n\n### 4.2 Dimension 2: Network Diversity (Effective Size & Constraint)\n\nNetwork diversity measures how **non-redundant** an influencer's connections are. We use two related metrics:\n\n- **Constraint** (Burt's structural holes): Lower constraint = more diverse, non-redundant contacts\n- **Effective Size**: Number of non-redundant contacts (higher = more diversity)\n\n::: {.callout-tip}\n## Why Diversity Matters\n\nAn influencer with 100 connections who all know each other (high redundancy) reaches essentially one community. An influencer with 100 diverse connections who don't know each other (low redundancy) reaches multiple distinct communities, multiplying campaign impact.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check if the qualified network has edges\nif(ecount(g_qualified) == 0) {\n  cat(\"WARNING: Qualified network has no edges. Using full network for diversity analysis.\\n\")\n  g_for_diversity <- g_full\n  # Filter to only qualified IDs after calculating on full network\n  use_full_network <- TRUE\n} else {\n  g_for_diversity <- g_qualified\n  use_full_network <- FALSE\n}\n\n# Calculate constraint (inverse measure of diversity)\n# Lower constraint = more structural holes = more diverse network\nconstraint_scores <- constraint(g_for_diversity)\n\n# Replace NA values (nodes with no connections or isolated) with 1 (maximum constraint)\nconstraint_scores[is.na(constraint_scores)] <- 1\n\n# Calculate effective size (Burt's measure of non-redundant contacts)\n# Higher effective size = more diverse contacts\nego_sizes <- ego_size(g_for_diversity, order = 1, mode = \"all\")\neffective_size <- ego_sizes - constraint_scores * ego_sizes\n\n# Replace NA in effective size with 0\neffective_size[is.na(effective_size)] <- 0\n\n# Create diversity metrics dataframe\ndiversity_metrics <- data.frame(\n  ID = as.numeric(V(g_for_diversity)$name),\n  constraint = constraint_scores,\n  effective_size = effective_size,\n  diversity_score = 1 - constraint_scores  # Convert to 0-1 scale (higher = more diverse)\n)\n\n# If we used full network, filter to only qualified IDs\nif(use_full_network) {\n  diversity_metrics <- diversity_metrics %>%\n    filter(ID %in% qualified_ids)\n}\n\n# Final cleanup and arrange\ndiversity_metrics <- diversity_metrics %>%\n  filter(!is.na(diversity_score)) %>%  # Remove any remaining NA values\n  arrange(constraint)  # Arrange by lowest constraint (highest diversity)\n\ncat(\"\\n=== NETWORK DIVERSITY SUMMARY ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== NETWORK DIVERSITY SUMMARY ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nConstraint (lower = more diverse):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nConstraint (lower = more diverse):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(diversity_metrics$constraint))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n0.07211 0.27273 0.55864 0.63262 1.00000 1.00000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nEffective Size (higher = more diverse):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEffective Size (higher = more diverse):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(diversity_metrics$effective_size))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   1.330   3.018   3.750  21.806 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Top 10 by network diversity\ncat(\"\\n=== TOP 10 BY NETWORK DIVERSITY ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== TOP 10 BY NETWORK DIVERSITY ===\n```\n\n\n:::\n\n```{.r .cell-code}\ntop_diversity <- diversity_metrics %>%\n  head(10) %>%\n  left_join(nodes, by = \"ID\") %>%\n  select(ID, Channel_ID, constraint, effective_size, diversity_score, Views)\n\nkable(top_diversity, caption = \"Top 10 Streamers by Network Diversity (Lowest Constraint)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Streamers by Network Diversity (Lowest Constraint)\n\n|   ID| Channel_ID| constraint| effective_size| diversity_score|     Views|\n|----:|----------:|----------:|--------------:|---------------:|---------:|\n| 4949|   23735582|  0.0721089|       19.48571|       0.9278911|  46682923|\n| 2740|   27121969|  0.0819644|       21.11482|       0.9180356|  13481914|\n| 1924|   60264946|  0.0914099|       21.80616|       0.9085901|  15814669|\n| 5842|    3481156|  0.0937017|       19.03227|       0.9062983|   7448777|\n| 4374|   65939429|  0.0939928|       17.21414|       0.9060072|    926412|\n| 5393|   56602918|  0.1020118|       11.67385|       0.8979882|   2838642|\n| 1883|   39677337|  0.1032008|       12.55519|       0.8967992|  34356681|\n| 5969|   54146574|  0.1033126|       15.24369|       0.8966874|   2805793|\n| 6136|   27942990|  0.1041093|       10.75069|       0.8958907| 178500544|\n| 2466|   49780445|  0.1074364|       10.71076|       0.8925636|   6613988|\n\n\n:::\n:::\n\n\n### 4.3 Integrating Both Dimensions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine degree and diversity metrics\ncombined_metrics <- degree_metrics %>%\n  inner_join(diversity_metrics, by = \"ID\") %>%  # Use inner_join to keep only matched records\n  left_join(nodes, by = \"ID\") %>%\n  filter(!is.na(constraint), !is.na(diversity_score)) %>%  # Remove any NA diversity scores\n  mutate(\n    # Normalize metrics to 0-100 scale for comparison\n    size_score = (total_degree - min(total_degree)) /\n                 (max(total_degree) - min(total_degree)) * 100,\n    diversity_score_scaled = diversity_score * 100\n  )\n\n# Calculate median splits for quadrant analysis (with na.rm=TRUE for safety)\nmedian_size <- median(combined_metrics$size_score, na.rm = TRUE)\nmedian_diversity <- median(combined_metrics$diversity_score_scaled, na.rm = TRUE)\n\ncat(\"\\n=== QUADRANT THRESHOLDS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== QUADRANT THRESHOLDS ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median Network Size Score:\", round(median_size, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian Network Size Score: 8.7 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median Diversity Score:\", round(median_diversity, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian Diversity Score: 44.14 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Valid candidates with scores:\", nrow(combined_metrics), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValid candidates with scores: 197 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Assign quadrants\ncombined_metrics <- combined_metrics %>%\n  mutate(\n    quadrant = case_when(\n      size_score >= median_size & diversity_score_scaled >= median_diversity ~ \"High Size, High Diversity\\n(OPTIMAL)\",\n      size_score >= median_size & diversity_score_scaled < median_diversity ~ \"High Size, Low Diversity\\n(Redundant)\",\n      size_score < median_size & diversity_score_scaled >= median_diversity ~ \"Low Size, High Diversity\\n(Niche)\",\n      size_score < median_size & diversity_score_scaled < median_diversity ~ \"Low Size, Low Diversity\\n(Peripheral)\",\n      TRUE ~ \"Uncategorized\"  # Catch-all for any edge cases\n    )\n  )\n\n# Count by quadrant\nquadrant_summary <- combined_metrics %>%\n  count(quadrant) %>%\n  arrange(desc(n))\n\ncat(\"\\n=== DISTRIBUTION ACROSS QUADRANTS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== DISTRIBUTION ACROSS QUADRANTS ===\n```\n\n\n:::\n\n```{.r .cell-code}\nkable(quadrant_summary, caption = \"Number of Candidates in Each Quadrant\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Number of Candidates in Each Quadrant\n\n|quadrant                            |  n|\n|:-----------------------------------|--:|\n|High Size, High Diversity\n(OPTIMAL)  | 99|\n|Low Size, Low Diversity\n(Peripheral) | 91|\n|High Size, Low Diversity\n(Redundant) |  7|\n\n\n:::\n:::\n\n\n## 5. Visualization: The 2�2 Strategic Framework\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define colors for quadrants\nquadrant_colors <- c(\n  \"High Size, High Diversity\\n(OPTIMAL)\" = \"#27ae60\",      # Green\n  \"High Size, Low Diversity\\n(Redundant)\" = \"#f39c12\",     # Orange\n  \"Low Size, High Diversity\\n(Niche)\" = \"#3498db\",         # Blue\n  \"Low Size, Low Diversity\\n(Peripheral)\" = \"#95a5a6\"      # Gray\n)\n\n# Create the main quadrant plot\np1 <- ggplot(combined_metrics, aes(x = size_score, y = diversity_score_scaled)) +\n  # Add quadrant backgrounds\n  annotate(\"rect\", xmin = -Inf, xmax = median_size,\n           ymin = median_diversity, ymax = Inf,\n           fill = \"#3498db\", alpha = 0.1) +\n  annotate(\"rect\", xmin = median_size, xmax = Inf,\n           ymin = median_diversity, ymax = Inf,\n           fill = \"#27ae60\", alpha = 0.15) +\n  annotate(\"rect\", xmin = -Inf, xmax = median_size,\n           ymin = -Inf, ymax = median_diversity,\n           fill = \"#95a5a6\", alpha = 0.1) +\n  annotate(\"rect\", xmin = median_size, xmax = Inf,\n           ymin = -Inf, ymax = median_diversity,\n           fill = \"#f39c12\", alpha = 0.1) +\n\n  # Add median lines\n  geom_vline(xintercept = median_size, linetype = \"dashed\",\n             color = \"black\", size = 1) +\n  geom_hline(yintercept = median_diversity, linetype = \"dashed\",\n             color = \"black\", size = 1) +\n\n  # Add points colored by quadrant\n  geom_point(aes(color = quadrant, size = Views), alpha = 0.7) +\n\n  # Color scale\n  scale_color_manual(values = quadrant_colors) +\n  scale_size_continuous(range = c(2, 12), labels = comma) +\n\n  # Labels and theme\n  labs(\n    title = \"Influencer Selection Framework: Network Size vs. Diversity\",\n    subtitle = \"Twitch Streamers Analysis for Space Games Inc.\",\n    x = \"Network Size Score (Total Degree Centrality, Normalized)\",\n    y = \"Network Diversity Score (1 - Constraint, Normalized)\",\n    color = \"Strategic Quadrant\",\n    size = \"Total Views\",\n    caption = \"Note: Only showing qualified candidates (non-mature content, affiliate status)\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16, hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5, color = \"gray40\"),\n    legend.position = \"right\",\n    panel.grid.minor = element_blank()\n  ) +\n  guides(\n    color = guide_legend(override.aes = list(size = 5)),\n    size = guide_legend(override.aes = list(alpha = 1))\n  )\n\nprint(p1)\n```\n\n::: {.cell-output-display}\n![](perform_2_files/figure-html/quadrant-plot-1.png){width=1152}\n:::\n:::\n\n\n::: {.callout-important icon=false}\n## Interpreting the Quadrants\n\n**Top-Right (OPTIMAL - Green)**: High Size + High Diversity\n\n- Large network with diverse, non-redundant connections\n- Reaches multiple distinct communities\n- **Strategic Value**: Maximum reach with minimal overlap\n- **Priority**: First-choice candidates\n\n**Top-Left (NICHE - Blue)**: Low Size + High Diversity\n\n- Smaller network but highly diverse connections\n- Bridges different communities despite limited reach\n- **Strategic Value**: Access to specialized audiences\n- **Priority**: Secondary candidates for targeted segments\n\n**Bottom-Right (REDUNDANT - Orange)**: High Size + Low Diversity\n\n- Large network but highly interconnected/redundant\n- Reaches primarily one cohesive community\n- **Strategic Value**: Deep penetration in single segment\n- **Priority**: Use if targeting specific community\n\n**Bottom-Left (PERIPHERAL - Gray)**: Low Size + Low Diversity\n\n- Small, redundant network\n- Limited strategic value\n- **Priority**: Exclude from consideration\n:::\n\n## 6. Identifying Top Candidates\n\n### 6.1 Optimal Quadrant Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Focus on optimal quadrant (High Size, High Diversity)\noptimal_candidates <- combined_metrics %>%\n  filter(quadrant == \"High Size, High Diversity\\n(OPTIMAL)\") %>%\n  arrange(desc(size_score + diversity_score_scaled)) %>%  # Combined ranking\n  mutate(\n    combined_score = size_score + diversity_score_scaled,\n    rank = row_number()\n  )\n\ncat(\"\\n=== OPTIMAL QUADRANT CANDIDATES ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== OPTIMAL QUADRANT CANDIDATES ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total candidates in optimal quadrant:\", nrow(optimal_candidates), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal candidates in optimal quadrant: 99 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Top 15 optimal candidates\ntop_optimal <- optimal_candidates %>%\n  head(15) %>%\n  select(rank, ID, Channel_ID, total_degree, diversity_score,\n         size_score, diversity_score_scaled, combined_score, Views, Days_active)\n\nkable(top_optimal,\n      digits = 2,\n      caption = \"Top 15 Candidates in Optimal Quadrant (High Size + High Diversity)\",\n      col.names = c(\"Rank\", \"ID\", \"Channel ID\", \"Total Degree\", \"Diversity\",\n                    \"Size Score\", \"Diversity Score\", \"Combined Score\", \"Views\", \"Days Active\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 15 Candidates in Optimal Quadrant (High Size + High Diversity)\n\n| Rank|   ID| Channel ID| Total Degree| Diversity| Size Score| Diversity Score| Combined Score|     Views| Days Active|\n|----:|----:|----------:|------------:|---------:|----------:|---------------:|--------------:|---------:|-----------:|\n|    1| 1924|   60264946|           23|      0.91|     100.00|           90.86|         190.86|  15814669|        1651|\n|    2| 2740|   27121969|           22|      0.92|      95.65|           91.80|         187.46|  13481914|        2478|\n|    3| 4949|   23735582|           20|      0.93|      86.96|           92.79|         179.75|  46682923|        2632|\n|    4| 5842|    3481156|           20|      0.91|      86.96|           90.63|         177.59|   7448777|        3556|\n|    5| 4374|   65939429|           18|      0.91|      78.26|           90.60|         168.86|    926412|        1556|\n|    6| 6716|   71040143|           17|      0.88|      73.91|           88.45|         162.36|    971621|        1491|\n|    7| 5969|   54146574|           16|      0.90|      69.57|           89.67|         159.23|   2805793|        1747|\n|    8|  166|   54739364|           15|      0.89|      65.22|           88.51|         153.73|  20516537|        1736|\n|    9| 5428|      12665|           15|      0.87|      65.22|           87.16|         152.37|  24316020|        4161|\n|   10| 5979|   39892516|           14|      0.88|      60.87|           88.42|         149.29|    725379|        2080|\n|   11| 1883|   39677337|           13|      0.90|      56.52|           89.68|         146.20|  34356681|        2086|\n|   12| 2845|   76962228|           13|      0.88|      56.52|           88.14|         144.66|    963402|        1402|\n|   13| 5393|   56602918|           12|      0.90|      52.17|           89.80|         141.97|   2838642|        1704|\n|   14| 6136|   27942990|           11|      0.90|      47.83|           89.59|         137.42| 178500544|        2443|\n|   15| 2466|   49780445|           11|      0.89|      47.83|           89.26|         137.08|   6613988|        1834|\n\n\n:::\n:::\n\n\n### 6.2 Detailed Profile of Top 3 Recommendations\n\n\n```{.r .cell-code}\n# Select top 3 for detailed analysis\ntop_3 <- optimal_candidates %>%\n  head(3)\n\ncat(\"\\n=== TOP 3 RECOMMENDED INFLUENCERS ===\\n\\n\")\n```\n\n\n=== TOP 3 RECOMMENDED INFLUENCERS ===\n\n```{.r .cell-code}\nfor(i in 1:3) {\n  candidate <- top_3[i, ]\n\n  cat(\"---------------------------------------------------\\n\")\n  cat(\"RANK\", i, \"- Channel ID:\", candidate$Channel_ID, \"\\n\")\n  cat(\"---------------------------------------------------\\n\")\n\n  cat(\"\\n[NETWORK METRICS]\\n\")\n  cat(\"  *  Total Network Size:\", candidate$total_degree, \"connections\\n\")\n  cat(\"  *  In-Degree (Followers):\", candidate$in_degree, \"\\n\")\n  cat(\"  *  Out-Degree (Following):\", candidate$out_degree, \"\\n\")\n  cat(\"  *  Network Diversity Score:\", round(candidate$diversity_score, 3), \"\\n\")\n  cat(\"  *  Constraint (lower = better):\", round(candidate$constraint, 3), \"\\n\")\n  cat(\"  *  Effective Network Size:\", round(candidate$effective_size, 1), \"non-redundant contacts\\n\")\n\n  cat(\"\\n[ENGAGEMENT METRICS]\\n\")\n  cat(\"  *  Total Views:\", format(candidate$Views, big.mark = \",\"), \"\\n\")\n  cat(\"  *  Days Active:\", candidate$Days_active, \"\\n\")\n  cat(\"  *  Avg Views per Day:\", format(round(candidate$Views / candidate$Days_active), big.mark = \",\"), \"\\n\")\n\n  cat(\"\\n[STRATEGIC POSITIONING]\\n\")\n  cat(\"  *  Size Score (normalized):\", round(candidate$size_score, 1), \"/100\\n\")\n  cat(\"  *  Diversity Score (normalized):\", round(candidate$diversity_score_scaled, 1), \"/100\\n\")\n  cat(\"  *  Combined Score:\", round(candidate$combined_score, 1), \"/200\\n\")\n\n  cat(\"\\n[QUALIFICATION]\\n\")\n  cat(\"  *  Mature Content: NO (appropriate for 16+ audience)\\n\")\n  cat(\"  *  Affiliate Status: YES (professional monetization)\\n\")\n\n  cat(\"\\n[STRATEGIC VALUE]\\n\")\n  size_ok <- !is.na(candidate$size_score)\n  div_ok <- !is.na(candidate$diversity_score_scaled)\n  if(size_ok && div_ok && candidate$size_score > 75 && candidate$diversity_score_scaled > 75) {\n    cat(\"  *** EXCEPTIONAL - Top-tier size and diversity\\n\")\n  } else if(size_ok && div_ok && candidate$size_score > 60 && candidate$diversity_score_scaled > 60) {\n    cat(\"  ** STRONG - Well-balanced profile\\n\")\n  } else if(size_ok && div_ok) {\n    cat(\"  * GOOD - Solid candidate\\n\")\n  } else {\n    cat(\"  * Scores unavailable\\n\")\n  }\n\n  cat(\"\\n\")\n}\n```\n\n---------------------------------------------------\nRANK 1 - Channel ID: 60264946 \n---------------------------------------------------\n\n[NETWORK METRICS]\n  *  Total Network Size: 23 connections\n  *  In-Degree (Followers): 3 \n  *  Out-Degree (Following): 20 \n  *  Network Diversity Score: 0.909 \n  *  Constraint (lower = better): 0.091 \n  *  Effective Network Size: 21.8 non-redundant contacts\n\n[ENGAGEMENT METRICS]\n  *  Total Views: 15,814,669 \n  *  Days Active: 1651 \n  *  Avg Views per Day: 9,579 \n\n[STRATEGIC POSITIONING]\n  *  Size Score (normalized): 100 /100\n  *  Diversity Score (normalized): 90.9 /100\n  *  Combined Score: 190.9 /200\n\n[QUALIFICATION]\n  *  Mature Content: NO (appropriate for 16+ audience)\n  *  Affiliate Status: YES (professional monetization)\n\n[STRATEGIC VALUE]\n  *** EXCEPTIONAL - Top-tier size and diversity\n\n---------------------------------------------------\nRANK 2 - Channel ID: 27121969 \n---------------------------------------------------\n\n[NETWORK METRICS]\n  *  Total Network Size: 22 connections\n  *  In-Degree (Followers): 6 \n  *  Out-Degree (Following): 16 \n  *  Network Diversity Score: 0.918 \n  *  Constraint (lower = better): 0.082 \n  *  Effective Network Size: 21.1 non-redundant contacts\n\n[ENGAGEMENT METRICS]\n  *  Total Views: 13,481,914 \n  *  Days Active: 2478 \n  *  Avg Views per Day: 5,441 \n\n[STRATEGIC POSITIONING]\n  *  Size Score (normalized): 95.7 /100\n  *  Diversity Score (normalized): 91.8 /100\n  *  Combined Score: 187.5 /200\n\n[QUALIFICATION]\n  *  Mature Content: NO (appropriate for 16+ audience)\n  *  Affiliate Status: YES (professional monetization)\n\n[STRATEGIC VALUE]\n  *** EXCEPTIONAL - Top-tier size and diversity\n\n---------------------------------------------------\nRANK 3 - Channel ID: 23735582 \n---------------------------------------------------\n\n[NETWORK METRICS]\n  *  Total Network Size: 20 connections\n  *  In-Degree (Followers): 17 \n  *  Out-Degree (Following): 3 \n  *  Network Diversity Score: 0.928 \n  *  Constraint (lower = better): 0.072 \n  *  Effective Network Size: 19.5 non-redundant contacts\n\n[ENGAGEMENT METRICS]\n  *  Total Views: 46,682,923 \n  *  Days Active: 2632 \n  *  Avg Views per Day: 17,737 \n\n[STRATEGIC POSITIONING]\n  *  Size Score (normalized): 87 /100\n  *  Diversity Score (normalized): 92.8 /100\n  *  Combined Score: 179.7 /200\n\n[QUALIFICATION]\n  *  Mature Content: NO (appropriate for 16+ audience)\n  *  Affiliate Status: YES (professional monetization)\n\n[STRATEGIC VALUE]\n  *** EXCEPTIONAL - Top-tier size and diversity\n\n## 7. Community Detection for Portfolio Diversification\n\nTo maximize reach and minimize audience overlap, we should select influencers from **different communities** within the Twitch network.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Detect communities using Louvain algorithm\nset.seed(123)\ncommunities <- cluster_louvain(as.undirected(g_qualified))\n\n# Add community membership to metrics\ncombined_metrics <- combined_metrics %>%\n  mutate(\n    community = as.numeric(membership(communities)[as.character(ID)])\n  )\n\ncat(\"\\n=== COMMUNITY STRUCTURE ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== COMMUNITY STRUCTURE ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of communities detected:\", max(combined_metrics$community, na.rm = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of communities detected: 53 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Community size distribution\ncommunity_sizes <- combined_metrics %>%\n  count(community) %>%\n  arrange(desc(n))\n\ncat(\"\\nTop 10 communities by size:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTop 10 communities by size:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(head(community_sizes, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   community  n\n1          2 27\n2          7 27\n3          4 26\n4          1 22\n5         12 18\n6          3 15\n7         13 10\n8         11  3\n9         29  3\n10        23  2\n```\n\n\n:::\n\n```{.r .cell-code}\n# Identify optimal candidates by community\noptimal_by_community <- combined_metrics %>%\n  filter(quadrant == \"High Size, High Diversity\\n(OPTIMAL)\") %>%\n  group_by(community) %>%\n  arrange(desc(size_score + diversity_score_scaled)) %>%\n  slice_head(n = 1) %>%\n  ungroup() %>%\n  arrange(desc(size_score + diversity_score_scaled))\n\ncat(\"\\n=== BEST CANDIDATE FROM EACH MAJOR COMMUNITY ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== BEST CANDIDATE FROM EACH MAJOR COMMUNITY ===\n```\n\n\n:::\n\n```{.r .cell-code}\ntop_community_candidates <- optimal_by_community %>%\n  head(10) %>%\n  select(community, ID, Channel_ID, total_degree, diversity_score,\n         size_score, diversity_score_scaled, Views)\n\nkable(top_community_candidates,\n      digits = 2,\n      caption = \"Top Candidate from Each Major Community (for Portfolio Diversification)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top Candidate from Each Major Community (for Portfolio Diversification)\n\n| community|   ID| Channel_ID| total_degree| diversity_score| size_score| diversity_score_scaled|    Views|\n|---------:|----:|----------:|------------:|---------------:|----------:|----------------------:|--------:|\n|        12| 1924|   60264946|           23|            0.91|     100.00|                  90.86| 15814669|\n|         7| 2740|   27121969|           22|            0.92|      95.65|                  91.80| 13481914|\n|         2| 4949|   23735582|           20|            0.93|      86.96|                  92.79| 46682923|\n|         4| 5842|    3481156|           20|            0.91|      86.96|                  90.63|  7448777|\n|         1|  166|   54739364|           15|            0.89|      65.22|                  88.51| 20516537|\n|        13| 1883|   39677337|           13|            0.90|      56.52|                  89.68| 34356681|\n|         3|  581|  100484450|            9|            0.89|      39.13|                  88.89| 19383016|\n|        11| 1727|   54507525|            2|            0.50|       8.70|                  50.00|   198427|\n|        29| 3841|   24208138|            3|            0.44|      13.04|                  44.14| 25325120|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize communities with top candidates highlighted\ntop_3_ids <- top_3$ID\n\np2 <- ggplot(combined_metrics, aes(x = size_score, y = diversity_score_scaled)) +\n  # Background points colored by community\n  geom_point(aes(color = as.factor(community)), alpha = 0.4, size = 3) +\n\n  # Highlight top 3 candidates\n  geom_point(data = combined_metrics %>% filter(ID %in% top_3_ids),\n             aes(size = Views), color = \"red\", shape = 17, alpha = 0.9) +\n\n  # Add labels for top 3\n  ggrepel::geom_label_repel(\n    data = combined_metrics %>% filter(ID %in% top_3_ids),\n    aes(label = paste(\"Top\", match(ID, top_3_ids), \"\\nID:\", ID)),\n    box.padding = 1,\n    point.padding = 0.5,\n    segment.color = \"red\",\n    segment.size = 1,\n    size = 4,\n    fontface = \"bold\"\n  ) +\n\n  # Median lines\n  geom_vline(xintercept = median_size, linetype = \"dashed\", color = \"black\") +\n  geom_hline(yintercept = median_diversity, linetype = \"dashed\", color = \"black\") +\n\n  scale_size_continuous(range = c(8, 15), labels = comma) +\n  labs(\n    title = \"Community Structure with Top 3 Recommended Influencers\",\n    subtitle = \"Colors represent different communities detected by Louvain algorithm\",\n    x = \"Network Size Score\",\n    y = \"Network Diversity Score\",\n    color = \"Community\",\n    size = \"Views\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16, hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5, color = \"gray40\"),\n    legend.position = \"right\"\n  ) +\n  guides(color = \"none\")  # Too many communities to show legend\n\nprint(p2)\n```\n\n::: {.cell-output-display}\n![](perform_2_files/figure-html/community-visualization-1.png){width=1152}\n:::\n:::\n\n\n## 8. ROI Estimation Framework\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define ROI calculation parameters\nroi_params <- list(\n  game_price = 29.99,\n  baseline_conversion = 0.0002,  # 0.02% baseline conversion\n  influencer_uplift = 0.0004,    # Additional 0.04% from influencer\n  network_multiplier = 2.5,      # Indirect reach multiplier\n  influencer_fee_base = 1000,    # Base fee per influencer\n  influencer_fee_per_view = 0.001  # Additional fee per 1000 views\n)\n\n# Calculate expected ROI for top 3 candidates\nroi_analysis <- top_3 %>%\n  mutate(\n    # Estimate direct reach (followers)\n    direct_reach = in_degree,\n\n    # Estimate indirect reach (network effect)\n    indirect_reach = total_degree * roi_params$network_multiplier,\n\n    # Total potential reach\n    total_reach = direct_reach + indirect_reach,\n\n    # Expected conversions\n    conversions = total_reach * roi_params$influencer_uplift,\n\n    # Expected revenue\n    expected_revenue = conversions * roi_params$game_price,\n\n    # Estimated cost\n    estimated_cost = roi_params$influencer_fee_base +\n                     (Views / 1000 * roi_params$influencer_fee_per_view),\n\n    # ROI calculation\n    net_revenue = expected_revenue - estimated_cost,\n    roi_ratio = expected_revenue / estimated_cost,\n    roi_percent = (roi_ratio - 1) * 100\n  )\n\ncat(\"\\n=== ROI PROJECTIONS FOR TOP 3 CANDIDATES ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== ROI PROJECTIONS FOR TOP 3 CANDIDATES ===\n```\n\n\n:::\n\n```{.r .cell-code}\nroi_summary <- roi_analysis %>%\n  select(ID, Channel_ID, direct_reach, indirect_reach, total_reach,\n         conversions, expected_revenue, estimated_cost, net_revenue, roi_percent) %>%\n  mutate(\n    rank = row_number(),\n    across(c(conversions), ~round(., 1)),\n    across(c(expected_revenue, estimated_cost, net_revenue), ~round(., 2))\n  )\n\nkable(roi_summary,\n      digits = 1,\n      caption = \"ROI Projections for Top 3 Recommended Influencers\",\n      format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: ROI Projections for Top 3 Recommended Influencers\n\n|    ID| Channel_ID| direct_reach| indirect_reach| total_reach| conversions| expected_revenue| estimated_cost| net_revenue| roi_percent| rank|\n|-----:|----------:|------------:|--------------:|-----------:|-----------:|----------------:|--------------:|-----------:|-----------:|----:|\n| 1,924| 60,264,946|            3|           57.5|        60.5|           0|              0.7|        1,015.8|    -1,015.1|       -99.9|    1|\n| 2,740| 27,121,969|            6|           55.0|        61.0|           0|              0.7|        1,013.5|    -1,012.8|       -99.9|    2|\n| 4,949| 23,735,582|           17|           50.0|        67.0|           0|              0.8|        1,046.7|    -1,045.9|       -99.9|    3|\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n[TOTAL CAMPAIGN PROJECTIONS]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[TOTAL CAMPAIGN PROJECTIONS]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  *  Total Investment:\", format(sum(roi_summary$estimated_cost), big.mark = \",\"), \"USD\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  *  Total Investment: 3,075.97 USD\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  *  Total Expected Revenue:\", format(sum(roi_summary$expected_revenue), big.mark = \",\"), \"USD\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  *  Total Expected Revenue: 2.26 USD\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  *  Total Net Revenue:\", format(sum(roi_summary$net_revenue), big.mark = \",\"), \"USD\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  *  Total Net Revenue: -3,073.72 USD\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  *  Average ROI:\", round(mean(roi_summary$roi_percent), 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  *  Average ROI: -99.9 %\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## ROI Assumptions\n\nThese projections are **illustrative estimates** based on:\n\n- Industry-standard conversion rates for gaming influencer campaigns\n- Network multiplier effects observed in similar campaigns\n- Typical Twitch influencer pricing models\n\n**Actual results will vary** based on:\n\n- Content quality and authenticity\n- Campaign timing and execution\n- Competitive landscape\n- Game reception and reviews\n- Influencer-brand fit\n\n**Recommendation**: Use performance-based contracts with base fees plus conversion bonuses to align incentives and reduce risk.\n:::\n\n## 9. Strategic Recommendations\n\n### 9.1 Final Selection Criteria\n\nBased on the 2x2 framework analysis, we recommend the following selection approach:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create final recommendation set\nfinal_recommendations <- combined_metrics %>%\n  filter(quadrant == \"High Size, High Diversity\\n(OPTIMAL)\") %>%\n  arrange(desc(size_score + diversity_score_scaled)) %>%\n  head(5) %>%\n  mutate(\n    recommendation_tier = case_when(\n      row_number() <= 3 ~ \"PRIMARY\",\n      row_number() <= 5 ~ \"BACKUP\"\n    ),\n    combined_score = size_score + diversity_score_scaled\n  ) %>%\n  select(recommendation_tier, ID, Channel_ID, total_degree, in_degree,\n         diversity_score, size_score, diversity_score_scaled,\n         combined_score, Views, Days_active, community)\n\nkable(final_recommendations,\n      digits = 2,\n      caption = \"Final Influencer Recommendations with Backup Candidates\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Final Influencer Recommendations with Backup Candidates\n\n|recommendation_tier |   ID| Channel_ID| total_degree| in_degree| diversity_score| size_score| diversity_score_scaled| combined_score|    Views| Days_active| community|\n|:-------------------|----:|----------:|------------:|---------:|---------------:|----------:|----------------------:|--------------:|--------:|-----------:|---------:|\n|PRIMARY             | 1924|   60264946|           23|         3|            0.91|     100.00|                  90.86|         190.86| 15814669|        1651|        12|\n|PRIMARY             | 2740|   27121969|           22|         6|            0.92|      95.65|                  91.80|         187.46| 13481914|        2478|         7|\n|PRIMARY             | 4949|   23735582|           20|        17|            0.93|      86.96|                  92.79|         179.75| 46682923|        2632|         2|\n|BACKUP              | 5842|    3481156|           20|        16|            0.91|      86.96|                  90.63|         177.59|  7448777|        3556|         4|\n|BACKUP              | 4374|   65939429|           18|        12|            0.91|      78.26|                  90.60|         168.86|   926412|        1556|         2|\n\n\n:::\n:::\n\n\n### 9.2 Implementation Strategy\n\n::: {.callout-note icon=false}\n## Phase 1: Outreach & Negotiation (Week 1-2)\n\n**Actions**:\n\n1. Contact top 3 primary candidates simultaneously\n2. Share campaign brief and brand values\n3. Request media kits and rate cards\n4. Conduct background checks (content history, controversies)\n5. Negotiate performance-based contracts\n\n**Success Criteria**:\n\n- Secure commitments from 3 influencers\n- Finalize contracts with performance bonuses\n- Establish content guidelines and approval process\n:::\n\n::: {.callout-note icon=false}\n## Phase 2: Content Planning (Week 2-3)\n\n**Actions**:\n\n1. Provide early game access to influencers\n2. Develop authentic integration strategies\n3. Create unique discount codes for tracking\n4. Schedule coordinated launch timing\n5. Set up attribution tracking systems\n\n**Success Criteria**:\n\n- Influencers genuinely excited about game\n- Content plans approved by both parties\n- Tracking mechanisms operational\n:::\n\n::: {.callout-note icon=false}\n## Phase 3: Campaign Execution (Week 4)\n\n**Actions**:\n\n1. Launch coordinated campaign\n2. Monitor real-time performance\n3. Engage with community responses\n4. Provide support to influencers as needed\n5. Collect conversion data\n\n**Success Criteria**:\n\n- All 3 influencers deliver promised content\n- Positive audience reception\n- Measurable traffic and conversions\n- No brand safety incidents\n:::\n\n::: {.callout-note icon=false}\n## Phase 4: Analysis & Optimization (Week 5+)\n\n**Actions**:\n\n1. Calculate actual ROI by influencer\n2. Analyze which communities converted best\n3. Identify top-performing content types\n4. Document lessons learned\n5. Plan follow-up campaigns\n\n**Success Criteria**:\n\n- Comprehensive performance report\n- Data-driven insights for future campaigns\n- Foundation for long-term relationships\n:::\n\n## 10. Conclusions & Business Impact\n\n### Key Findings\n\n1. **Framework Validation**: The 2�2 framework (size � diversity) successfully identifies influencers with both reach and strategic positioning across multiple communities.\n\n2. **Quality Over Quantity**: Our analysis shows that qualified candidates in the optimal quadrant represent a small, strategic subset of all streamers, demonstrating that strategic network position is rare and valuable.\n\n3. **Portfolio Approach**: Top candidates span different communities, minimizing audience overlap and maximizing campaign reach.\n\n4. **ROI Potential**: Conservative estimates project positive ROI with potential upside if network effects exceed expectations.\n\n### Strategic Value Beyond ROI\n\nWhile ROI projections are positive, the strategic value extends beyond immediate sales:\n\n- **Brand Positioning**: Association with trusted community voices builds long-term credibility\n- **Market Intelligence**: Direct feedback from influential gamers informs product development\n- **Community Building**: Creates foundation for ongoing player engagement\n- **Competitive Advantage**: Early mover advantage in space strategy gaming segment on Twitch\n\n### Risk Mitigation\n\nThe 2x2 framework approach mitigates several key risks:\n\n- **Brand Safety**: Pre-filtering for non-mature content and professional status\n- **Portfolio Diversification**: Multiple influencers across different communities\n- **Strategic Alignment**: Focus on both reach (size) and impact (diversity)\n- **Measurable Results**: Performance-based contracts with clear attribution\n\n### Final Recommendation\n\n**Proceed with top 3 identified influencers**, ensuring they span different communities for maximum reach and minimum overlap.\n\n**Backup candidates** provide contingency options if primary negotiations fail.\n\n---\n\n::: {.callout-important}\n## Next Steps for Space Games Inc.\n\n1. **Validate Analysis**: Conduct qualitative review of top candidates' channels\n2. **Initiate Contact**: Reach out to top 3 + backups simultaneously\n3. **Negotiate Contracts**: Structure with base fee + performance bonuses\n4. **Prepare Assets**: Create influencer-specific game keys and discount codes\n5. **Monitor & Optimize**: Track performance and adjust strategy in real-time\n\n**Timeline**: Execute all phases within the 1-month window to launch deadline.\n:::\n\n---\n\n**Analysis Framework**: Network Size � Diversity (2�2 Strategic Framework)\n**Course**: SMM638 Network Analytics\n**Case Study**: Space Games Inc. - Twitch Influencer Campaign\n",
    "supporting": [
      "perform_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}