{
  "hash": "d6015dbe7fed7ae78763acb76d6dedd4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Twitch Network: Exploratory Data Analysis\"\nsubtitle: \"Week 3 - Network Analytics\"\ndate: \"today\"\nformat:\n  html:\n    toc: true\n    code-fold: show\n---\n\n\n\n## Introduction\n\nThis exploratory data analysis examines the Twitch network dataset, focusing on node attributes of Twitch streamers. The dataset includes information about streamer activity, content type, viewership, and affiliate status.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(scales)\nlibrary(knitr)\n\n# Set theme for plots\ntheme_set(theme_minimal())\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read the Twitch nodes data\ntwitch_nodes <- read_csv(\"../../../data/twitch/Twitch_nodes.csv\")\n\n# Display data structure\ncat(\"Dataset dimensions:\", nrow(twitch_nodes), \"rows,\", ncol(twitch_nodes), \"columns\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDataset dimensions: 7126 rows, 6 columns\n```\n\n\n:::\n:::\n\n\n## Data Overview\n\nThe Twitch dataset contains information about streamers including:\n- **ID**: Streamer identifier\n- **Days_active**: Number of days the streamer has been active\n- **Mature_content**: Whether the channel contains mature content (TRUE/FALSE)\n- **Views**: Total number of views\n- **Affiliate**: Whether the streamer has affiliate status (TRUE/FALSE)\n- **Channel_ID**: Unique channel identifier\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary table of data types\ndata_summary <- data.frame(\n  Variable = names(twitch_nodes),\n  Type = sapply(twitch_nodes, class),\n  Missing = sapply(twitch_nodes, function(x) sum(is.na(x))),\n  Unique = sapply(twitch_nodes, function(x) length(unique(x))),\n  stringsAsFactors = FALSE,\n  row.names = NULL\n)\n\nkable(data_summary, caption = \"Data Structure Summary\", row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\nTable: Data Structure Summary\n\n|Variable       |Type    | Missing| Unique|\n|:--------------|:-------|-------:|------:|\n|ID             |numeric |       0|   7126|\n|Days_active    |numeric |       0|   2565|\n|Mature_content |logical |       0|      2|\n|Views          |numeric |       0|   5822|\n|Affiliate      |logical |       0|      2|\n|Channel_ID     |numeric |       0|   7126|\n\n\n:::\n:::\n\n\n## Distribution Analysis\n\n### Views Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate summary statistics\nviews_summary <- twitch_nodes %>%\n  summarise(\n    Min = min(Views),\n    Q1 = quantile(Views, 0.25),\n    Median = median(Views),\n    Mean = mean(Views),\n    Q3 = quantile(Views, 0.75),\n    Max = max(Views)\n  )\n\nkable(views_summary, caption = \"Views Summary Statistics\", format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Views Summary Statistics\n\n| Min|    Q1|  Median|      Mean|     Q3|         Max|\n|---:|-----:|-------:|---------:|------:|-----------:|\n|   5| 1,743| 4,839.5| 193,470.2| 15,263| 178,500,544|\n\n\n:::\n\n```{.r .cell-code}\n# Create histogram with log scale\np1 <- ggplot(twitch_nodes, aes(x = Views)) +\n  geom_histogram(bins = 50, fill = \"#9146FF\", alpha = 0.8, color = \"white\") +\n  scale_x_log10(labels = comma) +\n  geom_vline(aes(xintercept = median(Views)), \n             color = \"red\", linetype = \"dashed\", size = 1) +\n  labs(title = \"Distribution of Channel Views (Log Scale)\",\n       subtitle = paste(\"Median:\", format(median(twitch_nodes$Views), big.mark = \",\")),\n       x = \"Views (log scale)\",\n       y = \"Number of Streamers\") +\n  theme(plot.title = element_text(hjust = 0.5, face = \"bold\"),\n        plot.subtitle = element_text(hjust = 0.5))\n\np1\n```\n\n::: {.cell-output-display}\n![](gamers_eda_files/figure-html/views-analysis-1.png){width=960}\n:::\n:::\n\n\n### Categorical Variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create summary tables\ncategorical_summary <- bind_rows(\n  twitch_nodes %>%\n    count(Mature_content) %>%\n    mutate(Variable = \"Mature Content\",\n           Category = as.character(Mature_content),\n           Percentage = round(n / sum(n) * 100, 1)),\n  \n  twitch_nodes %>%\n    count(Affiliate) %>%\n    mutate(Variable = \"Affiliate Status\",\n           Category = as.character(Affiliate),\n           Percentage = round(n / sum(n) * 100, 1))\n) %>%\n  select(Variable, Category, n, Percentage)\n\nkable(categorical_summary, caption = \"Categorical Variables Distribution\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Categorical Variables Distribution\n\n|Variable         |Category |    n| Percentage|\n|:----------------|:--------|----:|----------:|\n|Mature Content   |FALSE    | 3238|       45.4|\n|Mature Content   |TRUE     | 3888|       54.6|\n|Affiliate Status |FALSE    | 6742|       94.6|\n|Affiliate Status |TRUE     |  384|        5.4|\n\n\n:::\n:::\n\n\n## Relationship Analysis\n\n### Affiliate Status vs Views\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- twitch_nodes %>%\n  mutate(Affiliate = factor(Affiliate, \n                           levels = c(FALSE, TRUE),\n                           labels = c(\"Non-Affiliate\", \"Affiliate\"))) %>%\n  ggplot(aes(x = Affiliate, y = Views, fill = Affiliate)) +\n  geom_violin(alpha = 0.6) +\n  geom_boxplot(width = 0.2, alpha = 0.8) +\n  scale_y_log10(labels = comma) +\n  scale_fill_manual(values = c(\"#9146FF\", \"#1DB954\")) +\n  labs(title = \"Views Distribution by Affiliate Status\",\n       x = \"Affiliate Status\",\n       y = \"Views (log scale)\") +\n  theme(legend.position = \"none\",\n        plot.title = element_text(hjust = 0.5, face = \"bold\"))\n\np2\n```\n\n::: {.cell-output-display}\n![](gamers_eda_files/figure-html/affiliate-views-1.png){width=960}\n:::\n:::\n\n\n### Days Active vs Views\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(twitch_nodes, aes(x = Days_active, y = Views)) +\n  geom_point(aes(color = Affiliate, shape = Mature_content), \n             alpha = 0.6, size = 2) +\n  scale_y_log10(labels = comma) +\n  scale_color_manual(values = c(\"#9146FF\", \"#1DB954\"),\n                     labels = c(\"Non-Affiliate\", \"Affiliate\")) +\n  scale_shape_manual(values = c(16, 17),\n                     labels = c(\"Non-Mature\", \"Mature\")) +\n  geom_smooth(method = \"lm\", se = TRUE, alpha = 0.2) +\n  labs(title = \"Relationship between Days Active and Views\",\n       x = \"Days Active\",\n       y = \"Views (log scale)\",\n       color = \"Affiliate Status\",\n       shape = \"Content Type\") +\n  theme(plot.title = element_text(hjust = 0.5, face = \"bold\"))\n\np3\n```\n\n::: {.cell-output-display}\n![](gamers_eda_files/figure-html/scatter-analysis-1.png){width=960}\n:::\n:::\n\n\n## Cross-tabulation Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed cross-tabulation\ncross_analysis <- twitch_nodes %>%\n  group_by(Mature_content, Affiliate) %>%\n  summarise(\n    Count = n(),\n    Avg_Views = mean(Views),\n    Median_Views = median(Views),\n    Avg_Days_Active = mean(Days_active),\n    .groups = \"drop\"\n  ) %>%\n  mutate(\n    Avg_Views = round(Avg_Views),\n    Avg_Days_Active = round(Avg_Days_Active),\n    Mature_content = ifelse(Mature_content, \"Mature\", \"Non-Mature\"),\n    Affiliate = ifelse(Affiliate, \"Affiliate\", \"Non-Affiliate\")\n  )\n\nkable(cross_analysis, \n      caption = \"Average Metrics by Content Type and Affiliate Status\",\n      format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Average Metrics by Content Type and Affiliate Status\n\n|Mature_content |Affiliate     | Count| Avg_Views| Median_Views| Avg_Days_Active|\n|:--------------|:-------------|-----:|---------:|------------:|---------------:|\n|Non-Mature     |Non-Affiliate | 3,041|    18,934|        3,261|           1,487|\n|Non-Mature     |Affiliate     |   197| 4,393,289|      478,931|           1,966|\n|Mature         |Non-Affiliate | 3,701|    17,297|        5,584|           1,514|\n|Mature         |Affiliate     |   187| 2,094,097|      488,224|           1,913|\n\n\n:::\n:::\n\n\n## Statistical Tests\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Affiliate status comparison\naffiliate_test <- t.test(log10(Views + 1) ~ Affiliate, data = twitch_nodes)\ncat(\"T-test: Affiliate vs Non-Affiliate (log-transformed views)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT-test: Affiliate vs Non-Affiliate (log-transformed views)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t =\", round(affiliate_test$statistic, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt = -54.6025 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p-value =\", format.pval(affiliate_test$p.value), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value = < 2.22e-16 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean difference =\", round(diff(affiliate_test$estimate), 4), \"log units\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean difference = 2.095 log units\n```\n\n\n:::\n:::\n\n\n## Top Performers\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify top 10 channels by views\ntop_channels <- twitch_nodes %>%\n  arrange(desc(Views)) %>%\n  slice_head(n = 10) %>%\n  mutate(\n    Rank = row_number(),\n    Views = format(Views, big.mark = \",\"),\n    Content_Type = ifelse(Mature_content, \"Mature\", \"Non-Mature\"),\n    Status = ifelse(Affiliate, \"Affiliate\", \"Non-Affiliate\")\n  ) %>%\n  select(Rank, Channel_ID, Views, Days_active, Content_Type, Status)\n\nkable(top_channels, caption = \"Top 10 Twitch Channels by Views\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Twitch Channels by Views\n\n| Rank| Channel_ID|Views       | Days_active|Content_Type |Status    |\n|----:|----------:|:-----------|-----------:|:------------|:---------|\n|    1|   27942990|178,500,544 |        2443|Non-Mature   |Affiliate |\n|    2|   20786541|89,506,813  |        2784|Non-Mature   |Affiliate |\n|    3|   56648155|74,201,622  |        1703|Non-Mature   |Affiliate |\n|    4|     261715|49,482,563  |        3904|Non-Mature   |Affiliate |\n|    5|   23735582|46,682,923  |        2632|Non-Mature   |Affiliate |\n|    6|   19623411|35,482,126  |        2825|Mature       |Affiliate |\n|    7|   39677337|34,356,681  |        2086|Non-Mature   |Affiliate |\n|    8|     497952|32,861,608  |        3820|Mature       |Affiliate |\n|    9|   30623831|31,417,100  |        2338|Non-Mature   |Affiliate |\n|   10|   30281925|30,977,250  |        2351|Mature       |Affiliate |\n\n\n:::\n:::\n\n\n## Key Insights\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate key metrics\ninsights <- list(\n  total_streamers = nrow(twitch_nodes),\n  avg_views = mean(twitch_nodes$Views),\n  median_views = median(twitch_nodes$Views),\n  affiliate_rate = mean(twitch_nodes$Affiliate) * 100,\n  mature_content_rate = mean(twitch_nodes$Mature_content) * 100,\n  views_ratio = mean(twitch_nodes$Views) / median(twitch_nodes$Views)\n)\n```\n:::\n\n\n**Summary of Key Findings:**\n\n- **Total streamers analyzed**: 7,126\n- **Highly skewed viewership**: Average views (193,470) are 40x higher than median views (4,839.5), indicating extreme concentration\n- **Affiliate rate**: Only 5.4% of streamers have affiliate status\n- **Mature content**: 54.6% of channels are marked as mature\n- **Affiliate advantage**: Affiliate streamers have significantly higher viewership (p < 0.001)\n\nThis analysis provides context for understanding how node attributes might relate to network centrality measures in the Twitch streamer ecosystem.",
    "supporting": [
      "gamers_eda_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}