---
title: "Useful Links"
format: html
---

## Course Resources

### Official Course Materials
- [GitHub Repository](https://github.com/simoneSantoni/net-analysis-smm638)
- [Moodle Page](#) (login required)

### Network Analysis Tools

#### R Resources
- [igraph R Package](https://igraph.org/r/)
- [tidygraph Documentation](https://tidygraph.data-imaginist.com/)
- [ggraph Gallery](https://ggraph.data-imaginist.com/)
- [statnet Project](http://www.statnet.org/)

#### Python Resources
- [NetworkX Documentation](https://networkx.org/)
- [Python Graph Tool](https://graph-tool.skewed.de/)
- [PyVis Interactive Networks](https://pyvis.readthedocs.io/)

### Learning Resources

#### Online Textbooks
- [Network Science by Barabási](http://networksciencebook.com/) (Free)
- [Introduction to Network Science](http://www.bdu.edu.et/cde/sites/bdu.edu.et.cde/files/Introduction%20to%20Network%20Science_0.pdf)

#### Tutorials
- [Network Analysis with R](https://kateto.net/network-visualization)
- [NetworkX Tutorial](https://networkx.org/documentation/stable/tutorial.html)
- [CRAN Task View: Social Network Analysis](https://cran.r-project.org/web/views/SocialNetworks.html)

### Visualization Tools
- [Gephi](https://gephi.org/) - Open source network visualization
- [Cytoscape](https://cytoscape.org/) - Network visualization platform
- [D3.js Force Layout](https://observablehq.com/@d3/force-directed-graph) - Web-based networks

### Datasets
- [Stanford Large Network Dataset Collection](https://snap.stanford.edu/data/)
- [Network Repository](http://networkrepository.com/)
- [Konect - Network Collection](http://konect.cc/)

### Communities
- [INSNA](https://www.insna.org/) - International Network for Social Network Analysis
- [NetSci Society](https://netscisociety.net/)
- [Reddit r/Networks](https://www.reddit.com/r/Networks/)